// src/react-router.tsx
import { Fragment, lazy, Suspense } from 'react'
import { ActionFunctionArgs, createBrowserRouter, LoaderFunctionArgs, Outlet, RouterProvider } from 'react-router-dom'
import type { ActionFunction, RouteObject, LoaderFunction } from 'react-router-dom'

import { generatePreservedRoutes, generateRegularRoutes } from './core'

export type Element = () => JSX.Element
export type Module = { default: Element; Loader: LoaderFunction; Action: ActionFunction; ErrorElement: Element }

const PRESERVED = import.meta.glob<Module>('/src/pages/(_app|404).{jsx,tsx}', { eager: true })
const ROUTES = import.meta.glob<Module>(['/src/pages/**/[\\w[]*.{jsx,tsx}', '!**/(_app|404).*'])

const preservedRoutes = generatePreservedRoutes<Element>(PRESERVED)

export const buildRegularRoute = (module: () => Promise<Module>, key: string) => {
  const Element = lazy(module)
  const ErrorElement = lazy(() => module().then((module) => ({ default: module.ErrorElement })))
  const index = /index\.(jsx|tsx)$/.test(key) ? { index: true } : {}

  return {
    ...index,
    element: <Suspense fallback={null} children={<Element />} />,
    loader: async (...args: [LoaderFunctionArgs]) => module().then((mod) => mod?.Loader?.(...args)),
    action: async (...args: [ActionFunctionArgs]) => module().then((mod) => mod?.Action?.(...args)),
    errorElement: <Suspense fallback={null} children={<ErrorElement />} />,
  }
}

const regularRoutes = generateRegularRoutes<RouteObject, () => Promise<Module>>(ROUTES, buildRegularRoute)

const App = preservedRoutes?.['_app'] || Fragment
const NotFound = preservedRoutes?.['404'] || Fragment

export const routes = [...regularRoutes, { path: '*', element: <NotFound /> }]
const router = createBrowserRouter([{ element: <App children={<Outlet />} />, children: routes }])

export const Routes = () => {
  return <RouterProvider router={router} />
}

// src/solid-router.tsx
/** @jsxImportSource solid-js */
import { Component, lazy, ParentProps } from 'solid-js'
import { RouteDataFunc, RouteDataFuncArgs, RouteDefinition, Router, useRoutes } from '@solidjs/router'

import { generatePreservedRoutes, generateRegularRoutes } from './core'

export type Module = { default: Component; Loader: RouteDataFunc }
type Route = { path?: string; component?: Component; children?: Route[] }

const PRESERVED = import.meta.glob<Module>('/src/pages/(_app|404).{jsx,tsx}', { eager: true })
const ROUTES = import.meta.glob<Module>(['/src/pages/**/[\\w[]*.{jsx,tsx}', '!**/(_app|404).*'])

const preservedRoutes = generatePreservedRoutes<Component>(PRESERVED)

export const buildRegularRoute = (module: () => Promise<Module>) => ({
  component: lazy(module),
  data: async (args: RouteDataFuncArgs) => module().then((mod) => mod?.Loader?.(args)),
})

const regularRoutes = generateRegularRoutes<Route, () => Promise<Module>>(ROUTES, buildRegularRoute)

const Fragment = (props: ParentProps) => <>{props.children}</>
const App = preservedRoutes?.['_app'] || Fragment
const NotFound = preservedRoutes?.['404'] || Fragment

export const routes = [...regularRoutes, { path: '*', component: <NotFound /> }] as RouteDefinition[]

export const Routes = () => {
  const Routes = useRoutes(routes)

  return (
    <Router>
      <App>
        <Routes />
      </App>
    </Router>
  )
}
